#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#spring.batch.initialize-schema: always
#
#jpa:
#  database-platform: org.hibernate.dialect.H2Dialect  # H2 데이터베이스용 Hibernate 방언
#  hibernate:
#    ddl-auto: update

#datasource
spring:
  datasource:
    hikari:
      idle-timeout: '10000'
      username: root
      maximum-pool-size: '10'
      driver-class-name: org.mariadb.jdbc.Driver
      connectionTimeout: '10000'
      max-lifetime: '580000'
      jdbc-url: jdbc:mariadb://localhost:3306/db1?autoReconnect=true
      password:
      connection-init-sql: SELECT 1 FROM DUAL
  batch:
    initialize-schema: always
